name: .NET

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]  

env:
  IMAGE_NAME: CargoHub
  OWNER: "${{ github.repository_owner }}"
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Add packages
      run: |
        dotnet add package Newtonsoft.Json
        dotnet add package xunit
    - name: Build
      run: dotnet build --no-restore

  test:
    needs: build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build the application
      run: dotnet build --configuration Release

    - name: Run application
      run: dotnet run --no-build --configuration Release --urls=http://0.0.0.0:3000 & sleep 5
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install httpx pytest coverage

    - name: Run integration tests
      run: coverage run -m pytest 

    - name: Run code coverage
      run: |
        coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
        coverage report --fail-under=90

    - name: Store coverage report
      uses: actions/upload-artifact@v4
      with:
        path: coverage.xml
      if: ${{ failure() }}
      
    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    - name: Generate Coverage Report
      run: |
        export PATH="$PATH:/home/runner/.dotnet/tools"
        reportgenerator -reports:"./test/TestResults/**/coverage.cobertura.xml" \
        -targetdir:"coverage-report" \
        -reporttypes:Html
      env:
        PATH: $PATH:/home/runner/.dotnet/tools
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1