name: .NET

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]  

env:
  IMAGE_NAME: CargoHub
  OWNER: "${{ github.repository_owner }}"
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version you are using

    - name: Build the application
      run: dotnet build --configuration Release

    - name: Run application
      run: dotnet run --no-build --configuration Release --urls=http://0.0.0.0:3000 & sleep 5
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install httpx pytest

    - name: Run integration tests
      run:  python -m pytest tests/integration